import { useMemo, useState } from 'react'
import { CalendarDays, CheckCircle2, Copy, GraduationCap, Pencil, Plus, Sparkles, Trash2 } from 'lucide-react'
import { useAppData } from '../context/useAppData.js'
import Badge from '../components/ui/Badge.jsx'
import Button from '../components/ui/Button.jsx'
import Card from '../components/ui/Card.jsx'
import Modal from '../components/ui/Modal.jsx'

const days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
const emptySubject = () => ({ name: '', examDate: '', internalExamDate: '', assignmentDeadline: '', projectDeadline: '', difficulty: 'medium', credits: '' })
const emptyLecture = (day = 'Monday') => ({ day, startTime: '09:00', endTime: '10:00', subject: '', room: '', faculty: '' })
const itemField = (type) => type === 'exam' ? 'exams' : `${type}s`
const dateLabel = (value) => value ? new Date(value).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' }) : 'Not scheduled'

export default function SemesterCopilot() {
  const data = useAppData()
  const { cache, createSemester, updateSemester, deleteSemester, addSubject, updateSubject, deleteSubject, addSemesterItem, updateSemesterItem, deleteSemesterItem, addTimetableLecture, updateTimetableLecture, deleteTimetableLecture } = data
  const semester = useMemo(() => (cache.semesters || []).find((item) => item.status === 'active') || null, [cache.semesters])
  const [creating, setCreating] = useState(false)
  const [name, setName] = useState('')
  const [subjects, setSubjects] = useState(() => Array.from({ length: 4 }, emptySubject))
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const [editor, setEditor] = useState(null)

  const run = async (action) => {
    setBusy(true); setError('')
    try { await action(); setEditor(null) } catch (currentError) { setError(currentError.message) } finally { setBusy(false) }
  }

  const submitSemester = (event) => {
    event.preventDefault()
    const validSubjects = subjects.filter((subject) => subject.name.trim())
    if (!name.trim() || !validSubjects.length) { setError('Add a semester name and at least one subject.'); return }
    run(async () => { await createSemester({ manualEntry: { semester: name.trim(), subjects: validSubjects.map((subject) => ({ ...subject, credits: Number(subject.credits) || 0 })) } }); setCreating(false); setName(''); setSubjects(Array.from({ length: 4 }, emptySubject)) })
  }

  if (!semester || creating) return <SemesterForm name={name} subjects={subjects} busy={busy} error={error} setName={setName} setSubjects={setSubjects} onSubmit={submitSemester} onCancel={semester ? () => setCreating(false) : null} />

  const saveEditor = (event) => {
    event.preventDefault()
    const { kind, mode, value, original } = editor
    if (kind === 'semester') return run(() => updateSemester(semester._id, { name: value.name }))
    if (kind === 'subject') return run(() => mode === 'add' ? addSubject(semester._id, value) : updateSubject(semester._id, original.id, value))
    if (kind === 'item') return run(() => mode === 'add' ? addSemesterItem(semester._id, value.type, value) : updateSemesterItem(semester._id, value.type, original.id, value))
    if (kind === 'lecture') return run(() => mode === 'add' ? addTimetableLecture(semester._id, value) : updateTimetableLecture(semester._id, original.id, value))
  }

  return <div className="page-semester mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
    <section className="rounded-3xl border border-accent-signal/20 bg-gradient-to-br from-accent-signal/20 via-bg-surface to-bg-surface p-6 surface-shadow sm:p-8">
      <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><div className="flex items-center gap-2 text-sm font-semibold text-accent-signal"><GraduationCap size={19} /> Guided academic setup</div><h1 className="mt-3 font-display text-3xl font-bold text-text-primary sm:text-4xl">Semester Copilot</h1><p className="mt-3 max-w-2xl text-text-secondary">Manage subjects, deadlines, revision, and your College Timetable in one place. Planner receives only actionable academic work.</p></div><div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={() => setCreating(true)}><Plus size={16} /> Add semester</Button><Button variant="secondary" onClick={() => setEditor({ kind: 'semester', mode: 'edit', value: { name: semester.name } })}><Pencil size={16} /> Edit</Button><button onClick={() => { if (window.confirm(`Delete ${semester.name}? Its generated Planner work will also be removed.`)) run(() => deleteSemester(semester._id)) }} className="rounded-xl border border-node-deadline/30 px-3 py-2 text-sm font-semibold text-node-deadline hover:bg-node-deadline/10"><Trash2 size={16} /></button></div></div>
    </section>
    {error && <p className="mt-5 rounded-xl border border-node-deadline/30 bg-node-deadline/10 px-4 py-3 text-sm text-node-deadline">{error}</p>}
    <div className="mt-8 grid gap-4 sm:grid-cols-3"><Metric label="Subjects" value={semester.subjects?.length || 0} /><Metric label="Upcoming exams" value={(semester.exams || []).length} /><Metric label="Important deadlines" value={(semester.assignments?.length || 0) + (semester.projects?.length || 0)} /></div>
    <Subjects semester={semester} onAdd={() => setEditor({ kind: 'subject', mode: 'add', value: emptySubject() })} onEdit={(subject) => setEditor({ kind: 'subject', mode: 'edit', original: subject, value: { ...subject, examDate: toInputDate(subject.examDate), internalExamDate: toInputDate(subject.internalExamDate), assignmentDeadline: toInputDate(subject.assignmentDeadline), projectDeadline: toInputDate(subject.projectDeadline) } })} onDelete={(subject) => { if (window.confirm(`Remove ${subject.name} and its generated deadlines?`)) run(() => deleteSubject(semester._id, subject.id)) }} />
    <AcademicCalendar semester={semester} onAdd={(type) => setEditor({ kind: 'item', mode: 'add', value: { type, title: '', subject: semester.subjects?.[0]?.name || '', date: '' } })} onEdit={(type, item) => setEditor({ kind: 'item', mode: 'edit', original: item, value: { type, title: item.title, subject: item.subject, date: toInputDate(item.date) } })} onDelete={(type, item) => { if (window.confirm(`Remove ${item.title}?`)) run(() => deleteSemesterItem(semester._id, type, item.id)) }} />
    <CollegeTimetable semester={semester} busy={busy} onAdd={(day) => setEditor({ kind: 'lecture', mode: 'add', value: emptyLecture(day) })} onEdit={(lecture) => setEditor({ kind: 'lecture', mode: 'edit', original: lecture, value: { ...lecture } })} onDelete={(lecture) => { if (window.confirm(`Delete ${lecture.subject}?`)) run(() => deleteTimetableLecture(semester._id, lecture.id)) }} onDuplicate={(lecture) => setEditor({ kind: 'lecture', mode: 'add', value: { ...lecture, id: '' } })} onCopyPrevious={(day) => run(async () => { const previous = days[days.indexOf(day) - 1]; const entries = (semester.collegeTimetable || []).filter((lecture) => lecture.day === previous); await Promise.all(entries.map((lecture) => addTimetableLecture(semester._id, { ...lecture, id: '', day }))) })} />
    <Card className="mt-6"><div className="flex gap-3"><CheckCircle2 className="shrink-0 text-node-resource" /><div><h2 className="font-display text-xl font-semibold text-text-primary">Planner stays actionable</h2><p className="mt-1 text-sm text-text-secondary">Assignments, projects, exam preparation, and revision tasks are synchronized with Planner. College Timetable lectures are visual only.</p></div></div></Card>
    {editor && <Editor editor={editor} subjects={semester.subjects || []} busy={busy} onChange={(value) => setEditor((current) => ({ ...current, value }))} onClose={() => setEditor(null)} onSave={saveEditor} />}
  </div>
}

function SemesterForm({ name, subjects, busy, error, setName, setSubjects, onSubmit, onCancel }) { const update = (index, field, value) => setSubjects((current) => current.map((subject, itemIndex) => itemIndex === index ? { ...subject, [field]: value } : subject)); return <div className="page-semester mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><section className="rounded-3xl border border-accent-signal/20 bg-gradient-to-br from-accent-signal/20 via-bg-surface to-bg-surface p-6 surface-shadow"><div className="flex items-center gap-2 text-sm font-semibold text-accent-signal"><GraduationCap size={19} /> Guided academic setup</div><h1 className="mt-3 font-display text-3xl font-bold text-text-primary">{onCancel ? 'Add Semester' : 'Semester Copilot'}</h1><p className="mt-2 text-text-secondary">Every date can be changed later.</p></section>{error && <p className="mt-5 rounded-xl border border-node-deadline/30 bg-node-deadline/10 px-4 py-3 text-sm text-node-deadline">{error}</p>}<form onSubmit={onSubmit} className="mt-8 space-y-6"><Card><Field label="Semester name" value={name} onChange={setName} placeholder="e.g. B.Tech Semester 5 — Fall 2026" /></Card><div className="grid gap-5 xl:grid-cols-2">{subjects.map((subject, index) => <Card key={index}><div className="flex items-center justify-between"><h2 className="font-display text-xl font-semibold text-text-primary">Subject {index + 1}</h2><Badge color="resource">{subject.difficulty}</Badge></div><SubjectFields subject={subject} onChange={(field, value) => update(index, field, value)} /></Card>)}</div><div className="flex gap-3"><Button size="lg" type="submit" disabled={busy}><Sparkles size={18} /> {busy ? 'Creating your semester...' : 'Create semester plan'}</Button>{onCancel && <Button type="button" variant="secondary" onClick={onCancel}>Cancel</Button>}</div></form></div> }

function Subjects({ semester, onAdd, onEdit, onDelete }) { return <Card className="mt-6"><div className="flex items-center justify-between gap-4"><div><h2 className="font-display text-2xl font-semibold text-text-primary">Subjects</h2><p className="mt-1 text-sm text-text-secondary">Names, credits, difficulty, and dates remain editable.</p></div><Button variant="secondary" onClick={onAdd}><Plus size={16} /> Add subject</Button></div><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{(semester.subjects || []).map((subject) => <div key={subject.id} className="rounded-xl border border-border-subtle bg-bg-base p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold text-text-primary">{subject.name}</p><p className="mt-1 text-xs text-text-muted">{subject.credits ? `${subject.credits} credits · ` : ''}{subject.difficulty || 'medium'}</p></div><div className="flex gap-1"><button onClick={() => onEdit(subject)} className="p-1 text-text-muted hover:text-accent-signal"><Pencil size={15} /></button><button onClick={() => onDelete(subject)} className="p-1 text-text-muted hover:text-node-deadline"><Trash2 size={15} /></button></div></div><p className="mt-3 text-xs text-text-secondary">Exam: {dateLabel(subject.examDate)}</p></div>)}</div></Card> }

function AcademicCalendar({ semester, onAdd, onEdit, onDelete }) { const groups = [['exam', 'Exams'], ['assignment', 'Assignments'], ['project', 'Projects']]; return <Card className="mt-6"><div><h2 className="font-display text-2xl font-semibold text-text-primary">Academic calendar</h2><p className="mt-1 text-sm text-text-secondary">Deadline changes immediately update Planner, Dashboard, and reminders.</p></div><div className="mt-6 grid gap-5 xl:grid-cols-3">{groups.map(([type, title]) => <div key={type} className="rounded-2xl border border-border-subtle bg-bg-base p-4"><div className="flex items-center justify-between"><h3 className="font-semibold text-text-primary">{title}</h3><button onClick={() => onAdd(type)} className="rounded-lg p-1.5 text-accent-signal hover:bg-accent-signal/10" aria-label={`Add ${type}`}><Plus size={17} /></button></div><div className="mt-3 space-y-2">{(semester[itemField(type)] || []).length === 0 ? <p className="py-3 text-sm text-text-muted">Nothing scheduled.</p> : (semester[itemField(type)] || []).slice().sort((a, b) => new Date(a.date) - new Date(b.date)).map((item) => <div key={item.id} className="rounded-xl border border-border-subtle bg-bg-elevated p-3"><p className="font-medium text-text-primary">{item.title}</p><p className="mt-1 text-xs text-text-muted">{item.subject} · {dateLabel(item.date)}</p><div className="mt-2 flex justify-end gap-1"><button onClick={() => onEdit(type, item)} className="p-1 text-text-muted hover:text-accent-signal"><Pencil size={14} /></button><button onClick={() => onDelete(type, item)} className="p-1 text-text-muted hover:text-node-deadline"><Trash2 size={14} /></button></div></div>)}</div></div>)}</div></Card> }

function CollegeTimetable({ semester, busy, onAdd, onEdit, onDelete, onDuplicate, onCopyPrevious }) { const lectures = semester.collegeTimetable || []; return <Card className="mt-6"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><div className="flex items-center gap-2 text-sm font-semibold text-accent-signal"><CalendarDays size={18} /> Separate from Planner</div><h2 className="mt-2 font-display text-2xl font-semibold text-text-primary">College Timetable</h2><p className="mt-1 text-sm text-text-secondary">Your manual weekly lecture schedule. Entries save automatically after each change.</p></div><Button variant="secondary" onClick={() => onAdd('Monday')}><Plus size={16} /> Add lecture</Button></div><div className="mt-6 grid gap-3 md:grid-cols-2 xl:grid-cols-7">{days.map((day, index) => { const dayLectures = lectures.filter((lecture) => lecture.day === day).slice().sort((a, b) => a.startTime.localeCompare(b.startTime)); return <div key={day} className="min-h-48 rounded-2xl border border-border-subtle bg-bg-base p-3"><div className="flex items-center justify-between gap-1"><p className="font-semibold text-text-primary">{day}</p><div className="flex"><button onClick={() => onAdd(day)} className="p-1 text-accent-signal" title={`Add ${day}`}><Plus size={15} /></button>{index > 0 && <button disabled={busy} onClick={() => onCopyPrevious(day)} className="p-1 text-text-muted hover:text-accent-signal disabled:opacity-50" title="Copy previous day"><Copy size={14} /></button>}</div></div><div className="mt-3 space-y-2">{dayLectures.length ? dayLectures.map((lecture) => <div key={lecture.id} className="rounded-xl border border-border-subtle bg-bg-elevated p-2.5"><p className="text-xs font-semibold text-accent-signal">{lecture.startTime} – {lecture.endTime}</p><p className="mt-1 text-sm font-semibold text-text-primary">{lecture.subject}</p>{(lecture.room || lecture.faculty) && <p className="mt-1 text-xs text-text-muted">{[lecture.room, lecture.faculty].filter(Boolean).join(' · ')}</p>}<div className="mt-2 flex justify-end gap-1"><button onClick={() => onDuplicate(lecture)} className="p-1 text-text-muted hover:text-accent-signal" title="Duplicate lecture"><Copy size={13} /></button><button onClick={() => onEdit(lecture)} className="p-1 text-text-muted hover:text-accent-signal"><Pencil size={13} /></button><button onClick={() => onDelete(lecture)} className="p-1 text-text-muted hover:text-node-deadline"><Trash2 size={13} /></button></div></div>) : <p className="py-4 text-xs text-text-muted">No lectures</p>}</div></div> })}</div></Card> }

function Editor({ editor, subjects, busy, onChange, onClose, onSave }) { const value = editor.value; const title = editor.kind === 'lecture' ? 'College Timetable lecture' : editor.kind === 'subject' ? 'Subject' : editor.kind === 'semester' ? 'Semester' : editor.value.type; return <Modal title={`${editor.mode === 'add' ? 'Add' : 'Edit'} ${title}`} onClose={onClose} className="max-w-md"><form onSubmit={onSave} className="mt-5"><div className="space-y-4">{editor.kind === 'semester' && <Field label="Semester name" value={value.name} onChange={(name) => onChange({ ...value, name })} />}{editor.kind === 'subject' && <SubjectFields subject={value} onChange={(field, next) => onChange({ ...value, [field]: next })} />}{editor.kind === 'item' && <><Field label="Title" value={value.title} onChange={(titleText) => onChange({ ...value, title: titleText })} /><label className="grid gap-2 text-xs font-semibold text-text-secondary">Subject<select value={value.subject} onChange={(event) => onChange({ ...value, subject: event.target.value })} className="rounded-xl border border-border-subtle bg-bg-base px-3 py-2.5 text-sm text-text-primary">{subjects.map((subject) => <option key={subject.id} value={subject.name}>{subject.name}</option>)}</select></label><Field label="Date" type="date" value={value.date} onChange={(date) => onChange({ ...value, date })} /></>}{editor.kind === 'lecture' && <><label className="grid gap-2 text-xs font-semibold text-text-secondary">Day<select value={value.day} onChange={(event) => onChange({ ...value, day: event.target.value })} className="rounded-xl border border-border-subtle bg-bg-base px-3 py-2.5 text-sm text-text-primary">{days.map((day) => <option key={day}>{day}</option>)}</select></label><div className="grid grid-cols-2 gap-3"><Field label="Start time" type="time" value={value.startTime} onChange={(startTime) => onChange({ ...value, startTime })} /><Field label="End time" type="time" value={value.endTime} onChange={(endTime) => onChange({ ...value, endTime })} /></div><Field label="Subject" value={value.subject} onChange={(subject) => onChange({ ...value, subject })} /><Field label="Room (optional)" value={value.room} onChange={(room) => onChange({ ...value, room })} /><Field label="Faculty (optional)" value={value.faculty} onChange={(faculty) => onChange({ ...value, faculty })} /></>}</div><div className="mt-6 flex justify-end gap-3"><Button type="button" variant="secondary" onClick={onClose}>Cancel</Button><Button type="submit" disabled={busy}>Save</Button></div></form></Modal> }

function SubjectFields({ subject, onChange }) { return <div className="mt-5 grid gap-3 sm:grid-cols-2"><Field label="Subject name" value={subject.name} onChange={(value) => onChange('name', value)} placeholder="e.g. Data Structures" /><Field label="Exam date" type="date" value={toInputDate(subject.examDate)} onChange={(value) => onChange('examDate', value)} /><Field label="Internal exam (optional)" type="date" value={toInputDate(subject.internalExamDate)} onChange={(value) => onChange('internalExamDate', value)} /><Field label="Assignment deadline (optional)" type="date" value={toInputDate(subject.assignmentDeadline)} onChange={(value) => onChange('assignmentDeadline', value)} /><Field label="Project deadline (optional)" type="date" value={toInputDate(subject.projectDeadline)} onChange={(value) => onChange('projectDeadline', value)} /><Field label="Credits (optional)" type="number" value={subject.credits} onChange={(value) => onChange('credits', value)} /><label className="grid gap-2 text-xs font-semibold text-text-secondary">Difficulty<select value={subject.difficulty || 'medium'} onChange={(event) => onChange('difficulty', event.target.value)} className="rounded-xl border border-border-subtle bg-bg-base px-3 py-2.5 text-sm text-text-primary outline-none focus:border-accent-signal"><option value="easy">Easy</option><option value="medium">Medium</option><option value="hard">Hard</option></select></label></div> }
function Field({ label, value, onChange, type = 'text', placeholder = '' }) { return <label className="grid gap-2 text-xs font-semibold text-text-secondary">{label}<input required={label === 'Subject name' || label === 'Title' || label === 'Subject'} type={type} value={value ?? ''} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className="rounded-xl border border-border-subtle bg-bg-base px-3 py-2.5 text-sm text-text-primary outline-none focus:border-accent-signal" /></label> }
function Metric({ label, value }) { return <Card className="p-5"><p className="text-sm text-text-secondary">{label}</p><p className="mt-1 font-display text-3xl font-bold text-text-primary">{value}</p></Card> }
function toInputDate(value) { return value ? new Date(value).toISOString().slice(0, 10) : '' }
